# This file is generated by tools/generate_api.py.
# Do not edit it directly.

from ._backend import xp
from .tensor import Tensor, _as_tensor

def zeros(*args, requires_grad=False, **kwargs):
    args = tuple(a.data if isinstance(a, Tensor) else a for a in args)
    fn = getattr(xp, name)
    return Tensor(fn(*args, **kwargs), requires_grad=requires_grad)

def ones(*args, requires_grad=False, **kwargs):
    args = tuple(a.data if isinstance(a, Tensor) else a for a in args)
    fn = getattr(xp, name)
    return Tensor(fn(*args, **kwargs), requires_grad=requires_grad)

def empty(*args, requires_grad=False, **kwargs):
    args = tuple(a.data if isinstance(a, Tensor) else a for a in args)
    fn = getattr(xp, name)
    return Tensor(fn(*args, **kwargs), requires_grad=requires_grad)

def full(*args, requires_grad=False, **kwargs):
    args = tuple(a.data if isinstance(a, Tensor) else a for a in args)
    fn = getattr(xp, name)
    return Tensor(fn(*args, **kwargs), requires_grad=requires_grad)

def arange(*args, requires_grad=False, **kwargs):
    args = tuple(a.data if isinstance(a, Tensor) else a for a in args)
    fn = getattr(xp, name)
    return Tensor(fn(*args, **kwargs), requires_grad=requires_grad)

def linspace(*args, requires_grad=False, **kwargs):
    args = tuple(a.data if isinstance(a, Tensor) else a for a in args)
    fn = getattr(xp, name)
    return Tensor(fn(*args, **kwargs), requires_grad=requires_grad)

def eye(*args, requires_grad=False, **kwargs):
    args = tuple(a.data if isinstance(a, Tensor) else a for a in args)
    fn = getattr(xp, name)
    return Tensor(fn(*args, **kwargs), requires_grad=requires_grad)

def zeros_like(*args, requires_grad=False, **kwargs):
    args = tuple(a.data if isinstance(a, Tensor) else a for a in args)
    fn = getattr(xp, name)
    return Tensor(fn(*args, **kwargs), requires_grad=requires_grad)

def ones_like(*args, requires_grad=False, **kwargs):
    args = tuple(a.data if isinstance(a, Tensor) else a for a in args)
    fn = getattr(xp, name)
    return Tensor(fn(*args, **kwargs), requires_grad=requires_grad)

def full_like(*args, requires_grad=False, **kwargs):
    args = tuple(a.data if isinstance(a, Tensor) else a for a in args)
    fn = getattr(xp, name)
    return Tensor(fn(*args, **kwargs), requires_grad=requires_grad)

def exp(x, *args, **kwargs):
    return _as_tensor(x).exp(*args, **kwargs)

def sum(x, *args, **kwargs):
    return _as_tensor(x).sum(*args, **kwargs)

def max(x, *args, **kwargs):
    return _as_tensor(x).max(*args, **kwargs)

def transpose(x, *args, **kwargs):
    return _as_tensor(x).transpose(*args, **kwargs)

def equal(x, *args, **kwargs):
    return _as_tensor(x).equal(*args, **kwargs)

__all__ = ['zeros', 'ones', 'empty', 'full', 'arange', 'linspace', 'eye', 'zeros_like', 'ones_like', 'full_like', 'exp', 'sum', 'max', 'transpose', 'equal']
