"""
Generates a file that creates torch API. It will generate torch.exp, torch.sum from Tensor methods.
It will also generate creation methods like torch.ones, torch.zeroes, etc.

I had to create this work around because:
1) I want as little boilerplate as possible.
   This way you have to write one new function into Tensor and then add its name
   to _api_spec.py and run the present code to generate new files.
   If you know a better way to avoid boilerplate, let me know.

2) You can just dynamically import these functions in __init__.py.
But the problem is static type checking errors.
"""

import runpy
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_DIR = PROJECT_ROOT / "mytorch"
SPEC_PATH = PACKAGE_DIR / "_api_spec.py"


def make_factory(name):
    return f"""
def {name}(*args, requires_grad=False, **kwargs):
    args = tuple(a.data if isinstance(a, Tensor) else a for a in args)
    fn = xp.{name}
    return Tensor(fn(*args, **kwargs), requires_grad=requires_grad)
"""


def make_op(name):
    return f"""
def {name}(x, *args, **kwargs):
    return _as_tensor(x).{name}(*args, **kwargs)
"""


def generate_operations(creation_ops, method_ops):
    parts = [
        "# This file is generated by tools/generate_api.py.",
        "# Do not edit it directly.",
        "",
        "from ._backend import xp",
        "from .tensor import Tensor, _as_tensor",
        "",
    ]
    creation_ops, method_ops = sorted(creation_ops), sorted(method_ops)

    for name in creation_ops:
        parts.append(make_factory(name).strip())
        parts.append("")

    for name in method_ops:
        parts.append(make_op(name).strip())
        parts.append("")

    exported_names = ",\n".join(repr(name) for name in sorted(creation_ops + method_ops))
    parts.append(f"__all__ = [\n{exported_names}\n]")
    parts.append("")

    return "\n".join(parts)


def generate_init(creation_ops, method_ops):
    names = (*creation_ops, *method_ops)
    names = sorted(names)

    imports = "\n".join(f"    {name}," for name in names)
    exported_names = ",\n".join(repr(name) for name in names)

    return f"""\
# This file is generated by tools/generate_api.py.
# Do not edit it directly.

from .tensor import Tensor
from ._generated import (
{imports}
)

__all__ = [
"Tensor",
{exported_names}
]
"""


def main():
    spec = runpy.run_path(str(SPEC_PATH))

    creation_ops = tuple(spec["CREATION_OPS"])
    method_ops = tuple(spec["METHOD_OPS"])

    generated_operations = generate_operations(
        creation_ops,
        method_ops,
    )
    generated_init = generate_init(
        creation_ops,
        method_ops,
    )

    (PACKAGE_DIR / "_generated.py").write_text(
        generated_operations,
        encoding="utf-8",
    )
    (PACKAGE_DIR / "__init__.py").write_text(
        generated_init,
        encoding="utf-8",
    )

    print("Generated:")
    print("  mytorch/_generated.py")
    print("  mytorch/__init__.py")


if __name__ == "__main__":
    main()
